config/routes.rb
Rails.application.routes.draw do

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :posts
  resources :sessions
  resources :friendships

  root 'sessions#new'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  

  belongs_to :user
  belongs_to :friend, :class_name => 'User', foreign_key: 'friend_id'

  validates :user_id, :uniqueness => {:scope => :friend_id}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user, counter_cache: true
  default_scope -> { order(created_at: :desc) }
  # validates :text, presence: true, length: {maximum: 140}
  # validates :title, presence: true
  # validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :friendships
  has_many :friends, through: :friendships

  has_secure_password
  # validates :username, presence: true, uniqueness: true, length: {maximum: 20}
  # validates :password, length: {minimum: 6}
  # validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController


  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    @friend = User.find(params[:friend_id])
    @user = current_user
    
    if @friendship.save
      UserMailer.friend_added_email(@friend, @user).deliver
      redirect_to users_path
      flash[:success] = "Added friend"
    else
      redirect_to users_path
      flash[:warning] = "Already friend"
    end
  end

  def destroy
    @friendship = current_user.friendships.find_by(:friend_id => params[:id])
    # @friend = User.find_by(:friend_id)
    # @user = current_user
    
    @friendship.destroy
      # UserMailer.friend_removed_email(@friend, @user).deliver
      flash[:info] = "Removed friendship"
      redirect_to users_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :update]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = current_user
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_path(@user)
      flash[:success] = "New post added"
    else
      flash[:danger] = "Try again"
      render :new
    end
  end

  def destroy
    if @user = current_user
      @user.posts.find(params[:id]).destroy
      redirect_to @user
      flash[:success] = "Post deleted"
    else
      redirect_to user_path(@user)
      flash[:warning] = "Can't delete friend post"
    end
  end

  def edit
    @user = current_user
    @post = @user.posts.find_by(params[:user_id])
  end

  def update
    @user = current_user
    @post = @user.posts.find_by(params[:user_id])
    if @post.update_attributes(post_params)
      redirect_to user_path(@user)
      flash[:success] = "Post updated"
    else
      flash[:warning] = "Try again"
      render 'edit'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    user = User.find_by_username(params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
      flash[:success] = 'Logged in'
    else
      flash.now[:danger] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to login_path
    flash[:info] = "Logged out"
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.where.not(id: current_user.id).decorate
    @friendship = current_user.friendships.find_by(:friend_id => params[:id])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver
      redirect_to login_path 
      flash[:success] = "Signed up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>
<body>
</br>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>

</body>
</html>

app/views/posts/edit.html.erb
<div class='text-center'>
<h3>Edit post</h3>

  <div class="container"> 
    <div class="text-center">
      <%= simple_form_for @post do |f| %>
        <%= f.input :title, label: false, placeholder: "Title" %>
        <%= f.input :text, label: false, placeholder: "Text" %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class='text-center'>
<h3>New post</h3>

  <div class="container"> 
    <div class="text-center">
      <%= simple_form_for @post do |f| %>
        <%= f.input :title, label: false, placeholder: "Title"  %>
        <%= f.input :text, label: false, placeholder: "Text"  %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="text-center">
  <h2>User: <%= link_to current_user.username, user_path(current_user) %></h2>

  <%= link_to "Log out", logout_path, method: :delete, class: 'btn btn-warning' %>

  <div class="container">
    <div class="text-center">
      <h4>Users list</h4>
      <table class="table">
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.username, user_path(id: user.id) %></td>
            <td><%= user.email %></td>
            <% if current_user.friendships.where(:friend_id => user.id).where(:user_id => current_user.id).empty? %>
              <td><%= link_to "Add Friend", friendships_path(:friend_id => user), method: :post, class: 'btn btn-info btn-xs' %></td>
            <% else %>
            <td><%= link_to "Remove", friendship_path(user), method: :delete, class: 'btn btn-danger btn-xs' %></td>
              
            <% end %>
          </tr>
          </br>
        <% end %>
      </table>
    </div>
  </div>

</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="container"> 
  <div class="text-left">
    <%= simple_form_for @user do |f| %>
      <%= f.input :username, label: false, placeholder: "Username" %>
      <%= f.input :email, label: false, placeholder: "Email" %>
      <%= f.input :password,label: false, placeholder: "Password" %>
      <%= f.input :password_confirmation, label: false, placeholder: "Password confirmation" %>
      <div class="text-center">
        <%= f.button :submit, class: 'btn btn-success' %>
    <% end %>

      <p>Already have account? <%= link_to "Log in", login_path %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-right">
  <%= link_to "Find Friends", users_path, method: :get %>
</div>

<div class='row'>
  <aside class="col-md-4">
    <section>
      <h4>Logged as: <%= link_to current_user.username, user_path(current_user) %></h4>
      <span><%= link_to "Log out", logout_path, method: :delete, class: 'btn btn-warning' %></span>
      <span><%= link_to "New post", new_post_path, class: 'btn btn-info' %><span>
    </section>

    <section>
      <h4>Your Friends</h4>
      <% if @user == current_user %>
        <ol>
          <% for user in @user.friends %>
            <li><%= link_to user.username, user_path(id: user.id) %>
            <span><%= link_to "Remove", friendship_path(user), method: :delete, class: 'btn btn-danger btn-xs' %></span></li>
          <% end %>
        </ol>
      <% end %>
    </section>
  </aside>

  <div class="col-md-8">
    <% if @user != current_user %>
      <h4>User: <%= @user.username %></h4>
    <% end %>

    <% @posts.each do |post| %>
    <strong><%= post.title %></strong></br>
    <%= post.text %></br>
      <% if @user == current_user %>
        <span><%= link_to "Edit", edit_post_path, class: 'btn btn-info btn-xs' %></span>
        <span><%= link_to "Delete", post_path(post), method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: "You sure?" } %></span></br>
      <% end %>
    <% end %>
  </div>
</div>

<%= @user.posts_count %>

<div class="text-center">
  <%= will_paginate @posts %>
</div>